### ISSUE TITLE
Could you add a release please ?

### ISSUE THREAD

**Issue by CelesteBlue-dev** [aerosoul94/ida_game_elf_loaders#2]
Please I would like to use VitaLDR.
Could you add compiled stuff in the release tab please ?
Thank you very much 😚

**Comment by aerosoul94** [comment]
I have a few more things I need to add and bugs to fix. On the next commit, I will add a release.

**Comment by aerosoul94** [comment]
https://github.com/aerosoul94/ida_gel/releases/tag/v1.0
