### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by VelocityRa** [aerosoul94/ida_game_elf_loaders#4]
Hello, I'm from the [Vita3K](https://github.com/Vita3K/Vita3K) project, I'd like to use some parts of https://github.com/aerosoul94/ida_game_elf_loaders/blob/master/src/vita/psp2_loader.cpp
but there's no license in the file/repo. Can you add one, or give me permission to use this here?

Thanks for your awesome work and for open-sourcing this, it's really helpful!

**Comment by aerosoul94** [comment]
Anyone can feel free to use any code they'd like from any of my projects that have no licensing. 

Thanks!
